name: Traffic Tracker
on:
  repository_dispatch:
    types: [v_*]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Received
        run: echo "Traffic signal captured successfully"
